_wandb:
    value:
        cli_version: 0.23.1
        e:
            svlkjvd0oc3yrqq8n0y5dk33umvfamro:
                codePath: classification_1\run_pipeline.py
                codePathLocal: run_pipeline.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "510808551424"
                        used: "354203066368"
                email: manthrishivaji13579@gmail.com
                executable: C:\Users\shiva\anaconda3\envs\new_mlops_env\python.exe
                git:
                    commit: c87f0e95977f3ab7e78212f906cf70313dce27be
                    remote: https://github.com/Shivaji125/ML.git
                gpu: NVIDIA GeForce GTX 1650 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 Ti
                      uuid: GPU-4e123ed2-5dfa-1462-8edb-9c4cbbc587b5
                host: predator001
                memory:
                    total: "8412778496"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\shiva\Desktop\Folder\gitpractise\ML\classification_1\run_pipeline.py
                python: CPython 3.9.23
                root: C:\Users\shiva\Desktop\Folder\gitpractise\ML\classification_1
                startedAt: "2025-12-27T15:19:37.037921Z"
                writerId: svlkjvd0oc3yrqq8n0y5dk33umvfamro
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.23
            "5": 0.23.1
            "8":
                - 2
                - 3
            "12": 0.23.1
            "13": windows-amd64
class_weight:
    value: balanced
max_iter:
    value: 500
model:
    value: LogisticRegression
random_state:
    value: 42
selection_metric:
    value: f1_score
solver:
    value: lbfgs
